Fixed manifest downloads and updated tests to use latest schemas.
BD2KGenomics/dcc-dashboard-service pull request #81
Opened 2018-06-16 07:37 UTC by jvlasblom

Fixes #58

2018-06-16 07:38 UTC, jvlasblom commented
This replaces my earlier PR https://github.com/DataBiosphere/cgp-dashboard-service/pull/77

2018-06-18 05:26 UTC, hannes-ucsc commented
@jvlasblom, I rebased your PR and resolved the conflicts. Please make sure you reset your local branch to the remote branch before adding commits.

2018-06-18 05:45 UTC, hannes-ucsc requested changes

2018-06-18 05:45 UTC, hannes-ucsc commented on chalicelib/responseobjects/elastic_request_builder.py
> +                facet.replace(".", "__")): values['is'] if 'is' in values else {}}))
`values.get('is', {})`

2018-06-18 05:45 UTC, hannes-ucsc commented on chalicelib/responseobjects/elastic_request_builder.py
> +            # Execute ElasticSearch request"
Remove quotes

2018-06-18 05:45 UTC, hannes-ucsc commented on chalicelib/responseobjects/hca_response_v5.py
> +        return [untranslated[es_name] if es_name in untranslated else "" for es_name in m.values()]
```
m = self.manifest_entries[keyname]
return [untranslated.get(es_name, "") for es_name in m.values()]
```

2018-06-18 05:45 UTC, hannes-ucsc commented on chalicelib/responseobjects/hca_response_v5.py
> +        writer.writerow(list(self.manifest_entries['bundles'].keys()) + list(self.manifest_entries['files'].keys()))
I don't think it is safe to assume that every iteration over `self.manifest_entries['bundles']` and `self.manifest_entries['files']` yields the entries in the same order. Can you please make those to mappings `OrderedDict`s?

2018-06-18 18:57 UTC, hannes-ucsc approved these changes

2018-06-18 19:49 UTC, hannes-ucsc approved these changes

2018-06-18 19:50 UTC, merged